config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
  root 'employees#home'

  get 'login', to: 'employees#login'
  post 'login', to: 'employees#login'
  get "/logout", to: "employees#logout"
  get 'signup', to: 'employees#signup', as: 'signup'
  post '/signup', to: 'employees#create'
  get 'admin_dashboard', to: 'employees#admin_dashboard', as: 'admin_dashboard'


  resources :employees, only: [:new, :show] do
    member do
      get 'upload'
    end
  end
  resources :admins, only: [:new, :create, :index, :show]

  resources :attendences, only: [] do
    collection do
      post :upload
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
  has_many :employees

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A[a-zA-Z0-9@._-]{3,80}\z/, message: "invalid_email_format" }
  validates :password, presence: true, format: { with: /\A(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{5,30}\z/, message: "invalid_password_format" }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendence.rb
class Attendence < ApplicationRecord
  belongs_to :employee

  def self.process_file(file)
    file_path = Rails.root.join('tmp', file.original_filename)
    File.open(file_path, 'wb') do |f|
      f.write(file.read)
    end
    json_data = JsonExcelConvert::Convert.excel_to_json(file_path)
    process_attendance(json_data)
  end

  def self.process_attendance(json_data)
    data = JSON.parse(json_data)
    data.each do |record|
      employee = Employee.find_by(email: record['Email'])
      if employee
        attendance = employee.attendences.find_or_initialize_by(date: record['Date'])
        attendance.update(
          working_hours: record['Working Hours'],
          leaves: record['Leaves'],
          attended: record['Attended']
        )
      end
    end
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :attendences
  belongs_to :admin

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A[a-zA-Z0-9@._-]{3,80}\z/, message: "invalid_email_format" }
  validates :password, presence: true, format: { with: /\A(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{5,30}\z/, message: "invalid_password_format" }

  has_secure_password

  def monthly_attendance
    attendences
      .where(date: Date.current.beginning_of_month..Date.current.end_of_month)
      .group_by_day(:date)
      .sum(:working_hours)
  end

  # Calculate the sum of working hours for the current year
  def yearly_attendance
    attendences
      .where(date: 1.year.ago.beginning_of_year..Date.current.end_of_year)
      .group_by_month(:date)
      .sum(:working_hours)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/attendences_controller.rb
class AttendencesController < ApplicationController
  protect_from_forgery with: :null_session

  def upload
    file = params[:file]
    if file.present?
      Attendence.process_file(file)
      redirect_to admin_dashboard_path, notice: 'Attendance records successfully uploaded.'
    else
      redirect_to admin_dashboard_path, alert: 'Please upload a file.'
    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :require_login, except: [:login, :signup, :new, :create, :home]
  before_action :correct_user, only: [:show]

  def home
    if logged_in?
      puts "current_user is: #{current_user.is_a?(Employee)}"
      redirect_to current_user.is_a?(Employee) ? employee_path(current_user) : admin_dashboard_path
    else
      render :login
    end
  end

  def login
    employee = Employee.find_by(email: login_params[:email])
    admin = Admin.find_by(email: login_params[:email])
    if employee&.authenticate(login_params[:password])
      log_in(employee)
      redirect_to employee_path(employee)
    elsif admin&.authenticate(login_params[:password])
      log_in(admin)
      redirect_to admin_dashboard_path
    else
      flash.now[:danger] = 'Invalid email or password'
      render :login, status: :unauthorized
    end
  end 

  def logout
    log_out
    redirect_to root_path, notice: 'Logged out successfully'
  end

  def signup
    @employee = Employee.new
    @admins = Admin.all
    render :new
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.create!(employee_params)
    redirect_to root_path, notice: 'Employee was successfully created' if @employee
  end

  def admin_dashboard
    if logged_in? && current_user.is_a?(Admin)
      @employees = Employee.page(params[:page]).per(10)
      @admin = current_user
    else
      flash[:danger] = 'You must be logged in as an admin to access this page.'
      redirect_to login_path
    end
  end

  def show
    @employee = Employee.find(params[:id])
    @monthly_attendance = @employee.monthly_attendance
    @yearly_attendance = @employee.yearly_attendance
    @total_hours = @employee.attendences.sum(:working_hours)
    @total_leaves = @employee.attendences.sum(:leaves)
    @total_days_attended = @employee.attendences.where(attended: true).count
  end

  def upload
    @employee = Employee.find(params[:id])
  end

  private

  def require_login
    unless logged_in?
      redirect_to root_path
    end
  end

  def correct_user
    @employee = Employee.find(params[:id])
    unless current_user == @employee || current_user.is_a?(Admin)
      flash[:danger] = 'You are not authorized to view this page.'
      redirect_to root_path
    end
  end

  def login_params
    params.require(:session).permit(:email, :password)
  end

  def employee_params
    params.require(:employee).permit(:name, :email, :password, :admin_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    if user.is_a?(Employee)
      session[:employee_id] = user.id
      session.delete(:admin_id)
    elsif user.is_a?(Admin)
      session[:admin_id] = user.id
      session.delete(:employee_id)
    end
  end

  def current_user
    @current_user ||= if session[:employee_id]
                        Employee.find_by(id: session[:employee_id])
                      elsif session[:admin_id]
                        Admin.find_by(id: session[:admin_id])
                      end
  end

  def logged_in?
    session[:employee_id] || session[:admin_id] ? true : false
  end

  def log_out
    session.delete(:employee_id)
    session.delete(:admin_id)
    @current_user = nil
  end
end

app/views/employees/admin_dashboard.html.erb
<div class="dashboard-container">
  <header class="dashboard-header">
    <div class="header">
      <h1>Admin Dashboard</h1>
      <div class="header-right">
        <span><%= @admin.email %></span>
        <%= link_to 'Logout', logout_path, data: { method: :delete }, class: 'btn btn-danger' %>
      </div>
    </div>
  </header>
  
  <%= form_with url: upload_attendences_path, local: true, multipart: true do %>
    <div class="file-upload">
      <label for="file">Upload Attendance File</label>
      <%= file_field_tag :file %>
      <%= submit_tag 'Upload Attendance', class: 'btn btn-primary' %>
    </div>
  <% end %>

  <table class="employee-table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <% @employees.each_with_index do |employee, index| %>
        <tr class="<%= 'row-even' if index.even? %>">
          <td><%= employee.name %></td>
          <td><%= employee.email %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @employees %>
</div>

app/views/employees/login.html.erb
<%= form_with(url: login_path, scope: :session, local: true) do |f| %>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6 col-lg-5">
        <div class="card mt-5 shadow-sm">
          <div class="card-body">
            <h1 class="card-title text-center mb-4">Login</h1>
            <div class="form-group mb-3">
              <%= f.label :email, class: 'form-label' %>
              <%= f.email_field :email, class: 'form-control', autofocus: true, required: true, placeholder: 'Enter your email' %>
            </div>

            <div class="form-group mb-4">
              <%= f.label :password, class: 'form-label' %>
              <%= f.password_field :password, class: 'form-control', required: true, placeholder: 'Enter your password' %>
            </div>

            <div class="d-grid mb-3">
              <%= f.submit 'Log in', class: 'btn btn-primary btn-block' %>
            </div>

            <div class="text-center">
              <%= link_to 'Sign up', signup_path, class: 'btn btn-link' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/employees/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-5">
      <div class="mt-3">
        <h1>Sign Up</h1>
      </div>
      <%= form_with model: @employee, url: signup_path, local: true do |form| %>
        <div class="form-group row mt-3">
          <%= form.label :email, "Email" %>
          <%= form.text_field :email, class: "form-control", placeholder: "Enter your email address", required: true %>
        </div>
        <div class="form-group row mt-3">
          <%= form.label :name, "Name" %>
          <%= form.text_field :name, class: "form-control", placeholder: "Enter your full name", required: true %>
        </div>
        <div class="form-group row mt-3">
          <%= form.label :password, "Password" %>
          <%= form.password_field :password, class: "form-control", placeholder: "Enter your password", required: true %>
        </div>
        <div class="form-group row mt-3">
          <%= form.label :password_confirmation, "Confirm password" %>
          <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Please enter the password again", required: true %>
        </div>
        <div class="form-group row mt-3">
          <%= form.label :admin_id, "Select Admin" %>
          <%= form.collection_select :admin_id, @admins, :id, :email, { prompt: "Select an admin" }, { class: "form-control", required: true } %>
        </div>
        <div class="form-group row mt-3">
          <%= form.submit "Sign Up", placeholder: " if you don't have an account", class: "btn btn-primary", id: "signup-button", disabled: true %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const adminSelect = document.querySelector('select[name="employee[admin_id]"]');
    const signupButton = document.getElementById('signup-button');

    adminSelect.addEventListener('change', function() {
      signupButton.disabled = adminSelect.value === "";
    });
  });
</script>

app/views/employees/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Employee Details</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_link_tag 'show_employee_details', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>
<body>
  <div class="header">
    <h1>Employee Details</h1>
    <div class="header-right">
      <span><%= current_user.email %></span>
      <%= link_to 'Logout', logout_path, data: { method: :DELETE }, class: 'btn btn-danger' %>
    </div>
  </div>
  <div class="statistics">
        <h2>Statistics</h2>
        <p>Total Working Hours: <%= @total_hours %></p>
        <p>Total Leaves: <%= @total_leaves %></p>
        <p>Total Days Attended: <%= @total_days_attended %></p>
    </div>
    <div class="charts">
        <h2>Monthly Attendance</h2>
        <%= bar_chart @monthly_attendance, xtitle: 'Date', ytitle: 'Working Hours' %>

        <h2>Yearly Attendance</h2>
        <%= bar_chart @yearly_attendance, xtitle: 'Month', ytitle: 'Working Hours' %>
    </div>
</body>
</html>

app/views/layouts/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="alert alert-<%= key == 'notice' ? 'info' : 'warning' %> mt-4">
    <%= message %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeAttendance</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "layouts/flash" %>
    <%= yield %>
  </body>
</html>